// src/app/layout.tsx
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import MuiProvider from "@/components/MuiProvider";
import { AuthProvider } from "@/context/AuthContext";
import { Toaster } from "react-hot-toast";

// Import your local font
const overusedGrotesk = localFont({
  src: "../../public/font/OverusedGrotesk-VF.woff2",
  variable: "--font-overused-grotesk",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${overusedGrotesk.variable} antialiased`}>
        <AuthProvider>
          <MuiProvider>
            {children}
            <Toaster />
          </MuiProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
